"use strict";
let fname;
fname = "Sean";
let newname = fname.toUpperCase();
console.log(newname);
let age;
age = 32;
let ageString = "32";
let inferAge = parseInt(ageString);
console.log(inferAge);
let isValid;
isValid = false;
console.log(isValid);
let empList;
empList = ["Matthew", "Mark", "John"];
console.log(empList);
let numList;
numList = [1, 2, 3, 4, 5];
let filterResult = numList.filter(num => num > 2);
console.log(numList);
console.log(filterResult);
let sum = numList.reduce((acc, num) => acc + num);
console.log(sum);
var Colour;
(function (Colour) {
    Colour[Colour["Red"] = 0] = "Red";
    Colour[Colour["Green"] = 1] = "Green";
    Colour[Colour["Blue"] = 2] = "Blue";
})(Colour || (Colour = {}));
let testRed = Colour.Red;
let testGreen = Colour.Green;
let testBlue = Colour.Blue;
console.log(testRed);
console.log(testGreen);
console.log(testBlue);
