"use strict";
let fname;
fname = "Sean";
let newname = fname.toUpperCase();
console.log(newname);
let age;
age = 32;
let ageString = "32";
let inferAge = parseInt(ageString);
console.log(inferAge);
let isValid;
isValid = false;
console.log(isValid);
let empList;
empList = ["Matthew", "Mark", "John"];
console.log(empList);
let numList;
numList = [1, 2, 3, 4, 5];
let filterResult = numList.filter(num => num > 2);
console.log(numList);
console.log(filterResult);
let sum = numList.reduce((acc, num) => acc + num);
console.log(sum);
let testRed = 0 /* Red */;
let testGreen = 1 /* Green */;
let testBlue = 2 /* Blue */;
console.log(testRed);
console.log(testGreen);
console.log(testBlue);
let numberThuple;
function swapNumbers(num1, num2) {
    return [num2, num1];
}
numberThuple = swapNumbers(1, 2);
console.log(numberThuple[1]);
let department;
department = "string value";
department = 100;
